FROM python:3.12-slim

WORKDIR /app

# КОПИРУЕМ ТЕКУЩУЮ ПАПКУ (backend/) → /app
COPY . .

# requirements.txt лежит в backend/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "auth.main:app", "--host", "0.0.0.0", "--port", "8000"]