name: Deploy to Swarm

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: frontend
          file: Dockerfile.frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/manage-content-frontend:latest

      - name: Build & Push Backend
        uses: docker/build-push-action@v5
        with:
          context: backend
          file: Dockerfile.backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/manage-content-backend:latest

      - name: Deploy to Swarm
        run: |
          curl -fsSL https://get.docker.com | sh
          docker stack deploy -c docker-compose.yml manage_content --with-registry-auth
        env:
          DOCKER_HOST: tcp://localhost:2376
